//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologicalRunPG.ElmaConnector {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebData", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WebData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnologicalRunPG.ElmaConnector.WebDataItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TechnologicalRunPG.ElmaConnector.WebDataItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebDataItem", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WebDataItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnologicalRunPG.ElmaConnector.WebData DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnologicalRunPG.ElmaConnector.WebData[] DataArrayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TechnologicalRunPG.ElmaConnector.WebData Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TechnologicalRunPG.ElmaConnector.WebData[] DataArray {
            get {
                return this.DataArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.DataArrayField, value) != true)) {
                    this.DataArrayField = value;
                    this.RaisePropertyChanged("DataArray");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfo", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class TaskInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        private long ExecutorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecutorNameField;
        
        private System.DateTime CreationDateField;
        
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnologicalRunPG.ElmaConnector.ConnectorInfo[] ConnectorInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long ExecutorId {
            get {
                return this.ExecutorIdField;
            }
            set {
                if ((this.ExecutorIdField.Equals(value) != true)) {
                    this.ExecutorIdField = value;
                    this.RaisePropertyChanged("ExecutorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExecutorName {
            get {
                return this.ExecutorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutorNameField, value) != true)) {
                    this.ExecutorNameField = value;
                    this.RaisePropertyChanged("ExecutorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public TechnologicalRunPG.ElmaConnector.ConnectorInfo[] ConnectorInfo {
            get {
                return this.ConnectorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectorInfoField, value) != true)) {
                    this.ConnectorInfoField = value;
                    this.RaisePropertyChanged("ConnectorInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectorInfo", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class ConnectorInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowMessageSendResult", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WorkflowMessageSendResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ReceivedCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReceivedCount {
            get {
                return this.ReceivedCountField;
            }
            set {
                if ((this.ReceivedCountField.Equals(value) != true)) {
                    this.ReceivedCountField = value;
                    this.RaisePropertyChanged("ReceivedCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/", ConfigurationName="ElmaConnector.WFPWebServiceSoap")]
    public interface WFPWebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Run", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.RunResponse Run(TechnologicalRunPG.ElmaConnector.RunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Run", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.RunResponse> RunAsync(TechnologicalRunPG.ElmaConnector.RunRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetStatus", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.GetStatusResponse GetStatus(TechnologicalRunPG.ElmaConnector.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.GetStatusResponse> GetStatusAsync(TechnologicalRunPG.ElmaConnector.GetStatusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/LoadContext", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.LoadContextResponse LoadContext(TechnologicalRunPG.ElmaConnector.LoadContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/LoadContext", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.LoadContextResponse> LoadContextAsync(TechnologicalRunPG.ElmaConnector.LoadContextRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetActiveTasks", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.GetActiveTasksResponse GetActiveTasks(TechnologicalRunPG.ElmaConnector.GetActiveTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetActiveTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.GetActiveTasksResponse> GetActiveTasksAsync(TechnologicalRunPG.ElmaConnector.GetActiveTasksRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/ExecuteTask", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.ExecuteTaskResponse ExecuteTask(TechnologicalRunPG.ElmaConnector.ExecuteTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/ExecuteTask", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.ExecuteTaskResponse> ExecuteTaskAsync(TechnologicalRunPG.ElmaConnector.ExecuteTaskRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SaveContext", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.SaveContextResponse SaveContext(TechnologicalRunPG.ElmaConnector.SaveContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SaveContext", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SaveContextResponse> SaveContextAsync(TechnologicalRunPG.ElmaConnector.SaveContextRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Terminate", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.TerminateResponse Terminate(TechnologicalRunPG.ElmaConnector.TerminateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Terminate", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.TerminateResponse> TerminateAsync(TechnologicalRunPG.ElmaConnector.TerminateRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessage", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.SendMessageResponse SendMessage(TechnologicalRunPG.ElmaConnector.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SendMessageResponse> SendMessageAsync(TechnologicalRunPG.ElmaConnector.SendMessageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessageToInstance", ReplyAction="*")]
        TechnologicalRunPG.ElmaConnector.SendMessageToInstanceResponse SendMessageToInstance(TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessageToInstance", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SendMessageToInstanceResponse> SendMessageToInstanceAsync(TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Run", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.RunRequestBody Body;
        
        public RunRequest() {
        }
        
        public RunRequest(TechnologicalRunPG.ElmaConnector.RunRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class RunRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string instanceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public TechnologicalRunPG.ElmaConnector.WebData data;
        
        public RunRequestBody() {
        }
        
        public RunRequestBody(string userName, string password, string token, string instanceName, TechnologicalRunPG.ElmaConnector.WebData data) {
            this.userName = userName;
            this.password = password;
            this.token = token;
            this.instanceName = instanceName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.RunResponseBody Body;
        
        public RunResponse() {
        }
        
        public RunResponse(TechnologicalRunPG.ElmaConnector.RunResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class RunResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long RunResult;
        
        public RunResponseBody() {
        }
        
        public RunResponseBody(long RunResult) {
            this.RunResult = RunResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(TechnologicalRunPG.ElmaConnector.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(TechnologicalRunPG.ElmaConnector.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(int GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadContextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadContext", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.LoadContextRequestBody Body;
        
        public LoadContextRequest() {
        }
        
        public LoadContextRequest(TechnologicalRunPG.ElmaConnector.LoadContextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class LoadContextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public LoadContextRequestBody() {
        }
        
        public LoadContextRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadContextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadContextResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.LoadContextResponseBody Body;
        
        public LoadContextResponse() {
        }
        
        public LoadContextResponse(TechnologicalRunPG.ElmaConnector.LoadContextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class LoadContextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnologicalRunPG.ElmaConnector.WebData LoadContextResult;
        
        public LoadContextResponseBody() {
        }
        
        public LoadContextResponseBody(TechnologicalRunPG.ElmaConnector.WebData LoadContextResult) {
            this.LoadContextResult = LoadContextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveTasks", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.GetActiveTasksRequestBody Body;
        
        public GetActiveTasksRequest() {
        }
        
        public GetActiveTasksRequest(TechnologicalRunPG.ElmaConnector.GetActiveTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetActiveTasksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public GetActiveTasksRequestBody() {
        }
        
        public GetActiveTasksRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveTasksResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.GetActiveTasksResponseBody Body;
        
        public GetActiveTasksResponse() {
        }
        
        public GetActiveTasksResponse(TechnologicalRunPG.ElmaConnector.GetActiveTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetActiveTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnologicalRunPG.ElmaConnector.TaskInfo[] GetActiveTasksResult;
        
        public GetActiveTasksResponseBody() {
        }
        
        public GetActiveTasksResponseBody(TechnologicalRunPG.ElmaConnector.TaskInfo[] GetActiveTasksResult) {
            this.GetActiveTasksResult = GetActiveTasksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteTask", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.ExecuteTaskRequestBody Body;
        
        public ExecuteTaskRequest() {
        }
        
        public ExecuteTaskRequest(TechnologicalRunPG.ElmaConnector.ExecuteTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class ExecuteTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long taskId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string connectorUid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public TechnologicalRunPG.ElmaConnector.WebData data;
        
        public ExecuteTaskRequestBody() {
        }
        
        public ExecuteTaskRequestBody(string userName, string password, long taskId, string connectorUid, TechnologicalRunPG.ElmaConnector.WebData data) {
            this.userName = userName;
            this.password = password;
            this.taskId = taskId;
            this.connectorUid = connectorUid;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteTaskResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.ExecuteTaskResponseBody Body;
        
        public ExecuteTaskResponse() {
        }
        
        public ExecuteTaskResponse(TechnologicalRunPG.ElmaConnector.ExecuteTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteTaskResponseBody {
        
        public ExecuteTaskResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContext", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.SaveContextRequestBody Body;
        
        public SaveContextRequest() {
        }
        
        public SaveContextRequest(TechnologicalRunPG.ElmaConnector.SaveContextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SaveContextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TechnologicalRunPG.ElmaConnector.WebData data;
        
        public SaveContextRequestBody() {
        }
        
        public SaveContextRequestBody(string userName, string password, long instanceId, TechnologicalRunPG.ElmaConnector.WebData data) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContextResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.SaveContextResponseBody Body;
        
        public SaveContextResponse() {
        }
        
        public SaveContextResponse(TechnologicalRunPG.ElmaConnector.SaveContextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveContextResponseBody {
        
        public SaveContextResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Terminate", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.TerminateRequestBody Body;
        
        public TerminateRequest() {
        }
        
        public TerminateRequest(TechnologicalRunPG.ElmaConnector.TerminateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class TerminateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reason;
        
        public TerminateRequestBody() {
        }
        
        public TerminateRequestBody(string userName, string password, long instanceId, string reason) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.reason = reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.TerminateResponseBody Body;
        
        public TerminateResponse() {
        }
        
        public TerminateResponse(TechnologicalRunPG.ElmaConnector.TerminateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TerminateResponseBody {
        
        public TerminateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(TechnologicalRunPG.ElmaConnector.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TechnologicalRunPG.ElmaConnector.WebData data;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string userName, string password, string messageTypeName, TechnologicalRunPG.ElmaConnector.WebData data) {
            this.userName = userName;
            this.password = password;
            this.messageTypeName = messageTypeName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(TechnologicalRunPG.ElmaConnector.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnologicalRunPG.ElmaConnector.WorkflowMessageSendResult SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(TechnologicalRunPG.ElmaConnector.WorkflowMessageSendResult SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageToInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageToInstance", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequestBody Body;
        
        public SendMessageToInstanceRequest() {
        }
        
        public SendMessageToInstanceRequest(TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageToInstanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public TechnologicalRunPG.ElmaConnector.WebData data;
        
        public SendMessageToInstanceRequestBody() {
        }
        
        public SendMessageToInstanceRequestBody(string userName, string password, long instanceId, string messageTypeName, TechnologicalRunPG.ElmaConnector.WebData data) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.messageTypeName = messageTypeName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageToInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageToInstanceResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public TechnologicalRunPG.ElmaConnector.SendMessageToInstanceResponseBody Body;
        
        public SendMessageToInstanceResponse() {
        }
        
        public SendMessageToInstanceResponse(TechnologicalRunPG.ElmaConnector.SendMessageToInstanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageToInstanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnologicalRunPG.ElmaConnector.WorkflowMessageSendResult SendMessageToInstanceResult;
        
        public SendMessageToInstanceResponseBody() {
        }
        
        public SendMessageToInstanceResponseBody(TechnologicalRunPG.ElmaConnector.WorkflowMessageSendResult SendMessageToInstanceResult) {
            this.SendMessageToInstanceResult = SendMessageToInstanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WFPWebServiceSoapChannel : TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFPWebServiceSoapClient : System.ServiceModel.ClientBase<TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap>, TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap {
        
        public WFPWebServiceSoapClient() {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFPWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.RunResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.Run(TechnologicalRunPG.ElmaConnector.RunRequest request) {
            return base.Channel.Run(request);
        }
        
        public long Run(string userName, string password, string token, string instanceName, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.RunRequest inValue = new TechnologicalRunPG.ElmaConnector.RunRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.RunRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.token = token;
            inValue.Body.instanceName = instanceName;
            inValue.Body.data = data;
            TechnologicalRunPG.ElmaConnector.RunResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).Run(inValue);
            return retVal.Body.RunResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.RunResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.RunAsync(TechnologicalRunPG.ElmaConnector.RunRequest request) {
            return base.Channel.RunAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.RunResponse> RunAsync(string userName, string password, string token, string instanceName, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.RunRequest inValue = new TechnologicalRunPG.ElmaConnector.RunRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.RunRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.token = token;
            inValue.Body.instanceName = instanceName;
            inValue.Body.data = data;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).RunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.GetStatusResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.GetStatus(TechnologicalRunPG.ElmaConnector.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public int GetStatus(string userName, string password, long instanceId) {
            TechnologicalRunPG.ElmaConnector.GetStatusRequest inValue = new TechnologicalRunPG.ElmaConnector.GetStatusRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.GetStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            TechnologicalRunPG.ElmaConnector.GetStatusResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.GetStatusResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.GetStatusAsync(TechnologicalRunPG.ElmaConnector.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.GetStatusResponse> GetStatusAsync(string userName, string password, long instanceId) {
            TechnologicalRunPG.ElmaConnector.GetStatusRequest inValue = new TechnologicalRunPG.ElmaConnector.GetStatusRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.GetStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.LoadContextResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.LoadContext(TechnologicalRunPG.ElmaConnector.LoadContextRequest request) {
            return base.Channel.LoadContext(request);
        }
        
        public TechnologicalRunPG.ElmaConnector.WebData LoadContext(string userName, string password, long instanceId) {
            TechnologicalRunPG.ElmaConnector.LoadContextRequest inValue = new TechnologicalRunPG.ElmaConnector.LoadContextRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.LoadContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            TechnologicalRunPG.ElmaConnector.LoadContextResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).LoadContext(inValue);
            return retVal.Body.LoadContextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.LoadContextResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.LoadContextAsync(TechnologicalRunPG.ElmaConnector.LoadContextRequest request) {
            return base.Channel.LoadContextAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.LoadContextResponse> LoadContextAsync(string userName, string password, long instanceId) {
            TechnologicalRunPG.ElmaConnector.LoadContextRequest inValue = new TechnologicalRunPG.ElmaConnector.LoadContextRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.LoadContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).LoadContextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.GetActiveTasksResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.GetActiveTasks(TechnologicalRunPG.ElmaConnector.GetActiveTasksRequest request) {
            return base.Channel.GetActiveTasks(request);
        }
        
        public TechnologicalRunPG.ElmaConnector.TaskInfo[] GetActiveTasks(string userName, string password, long instanceId) {
            TechnologicalRunPG.ElmaConnector.GetActiveTasksRequest inValue = new TechnologicalRunPG.ElmaConnector.GetActiveTasksRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.GetActiveTasksRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            TechnologicalRunPG.ElmaConnector.GetActiveTasksResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).GetActiveTasks(inValue);
            return retVal.Body.GetActiveTasksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.GetActiveTasksResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.GetActiveTasksAsync(TechnologicalRunPG.ElmaConnector.GetActiveTasksRequest request) {
            return base.Channel.GetActiveTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.GetActiveTasksResponse> GetActiveTasksAsync(string userName, string password, long instanceId) {
            TechnologicalRunPG.ElmaConnector.GetActiveTasksRequest inValue = new TechnologicalRunPG.ElmaConnector.GetActiveTasksRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.GetActiveTasksRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).GetActiveTasksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.ExecuteTaskResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.ExecuteTask(TechnologicalRunPG.ElmaConnector.ExecuteTaskRequest request) {
            return base.Channel.ExecuteTask(request);
        }
        
        public void ExecuteTask(string userName, string password, long taskId, string connectorUid, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.ExecuteTaskRequest inValue = new TechnologicalRunPG.ElmaConnector.ExecuteTaskRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.ExecuteTaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.taskId = taskId;
            inValue.Body.connectorUid = connectorUid;
            inValue.Body.data = data;
            TechnologicalRunPG.ElmaConnector.ExecuteTaskResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).ExecuteTask(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.ExecuteTaskResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.ExecuteTaskAsync(TechnologicalRunPG.ElmaConnector.ExecuteTaskRequest request) {
            return base.Channel.ExecuteTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.ExecuteTaskResponse> ExecuteTaskAsync(string userName, string password, long taskId, string connectorUid, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.ExecuteTaskRequest inValue = new TechnologicalRunPG.ElmaConnector.ExecuteTaskRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.ExecuteTaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.taskId = taskId;
            inValue.Body.connectorUid = connectorUid;
            inValue.Body.data = data;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).ExecuteTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.SaveContextResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.SaveContext(TechnologicalRunPG.ElmaConnector.SaveContextRequest request) {
            return base.Channel.SaveContext(request);
        }
        
        public void SaveContext(string userName, string password, long instanceId, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.SaveContextRequest inValue = new TechnologicalRunPG.ElmaConnector.SaveContextRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.SaveContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.data = data;
            TechnologicalRunPG.ElmaConnector.SaveContextResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).SaveContext(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SaveContextResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.SaveContextAsync(TechnologicalRunPG.ElmaConnector.SaveContextRequest request) {
            return base.Channel.SaveContextAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SaveContextResponse> SaveContextAsync(string userName, string password, long instanceId, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.SaveContextRequest inValue = new TechnologicalRunPG.ElmaConnector.SaveContextRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.SaveContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.data = data;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).SaveContextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.TerminateResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.Terminate(TechnologicalRunPG.ElmaConnector.TerminateRequest request) {
            return base.Channel.Terminate(request);
        }
        
        public void Terminate(string userName, string password, long instanceId, string reason) {
            TechnologicalRunPG.ElmaConnector.TerminateRequest inValue = new TechnologicalRunPG.ElmaConnector.TerminateRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.TerminateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.reason = reason;
            TechnologicalRunPG.ElmaConnector.TerminateResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).Terminate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.TerminateResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.TerminateAsync(TechnologicalRunPG.ElmaConnector.TerminateRequest request) {
            return base.Channel.TerminateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.TerminateResponse> TerminateAsync(string userName, string password, long instanceId, string reason) {
            TechnologicalRunPG.ElmaConnector.TerminateRequest inValue = new TechnologicalRunPG.ElmaConnector.TerminateRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.TerminateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.reason = reason;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).TerminateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.SendMessageResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.SendMessage(TechnologicalRunPG.ElmaConnector.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public TechnologicalRunPG.ElmaConnector.WorkflowMessageSendResult SendMessage(string userName, string password, string messageTypeName, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.SendMessageRequest inValue = new TechnologicalRunPG.ElmaConnector.SendMessageRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.SendMessageRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            TechnologicalRunPG.ElmaConnector.SendMessageResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SendMessageResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.SendMessageAsync(TechnologicalRunPG.ElmaConnector.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SendMessageResponse> SendMessageAsync(string userName, string password, string messageTypeName, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.SendMessageRequest inValue = new TechnologicalRunPG.ElmaConnector.SendMessageRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.SendMessageRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnologicalRunPG.ElmaConnector.SendMessageToInstanceResponse TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.SendMessageToInstance(TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequest request) {
            return base.Channel.SendMessageToInstance(request);
        }
        
        public TechnologicalRunPG.ElmaConnector.WorkflowMessageSendResult SendMessageToInstance(string userName, string password, long instanceId, string messageTypeName, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequest inValue = new TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            TechnologicalRunPG.ElmaConnector.SendMessageToInstanceResponse retVal = ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).SendMessageToInstance(inValue);
            return retVal.Body.SendMessageToInstanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SendMessageToInstanceResponse> TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap.SendMessageToInstanceAsync(TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequest request) {
            return base.Channel.SendMessageToInstanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechnologicalRunPG.ElmaConnector.SendMessageToInstanceResponse> SendMessageToInstanceAsync(string userName, string password, long instanceId, string messageTypeName, TechnologicalRunPG.ElmaConnector.WebData data) {
            TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequest inValue = new TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequest();
            inValue.Body = new TechnologicalRunPG.ElmaConnector.SendMessageToInstanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            return ((TechnologicalRunPG.ElmaConnector.WFPWebServiceSoap)(this)).SendMessageToInstanceAsync(inValue);
        }
    }
}
